# This Makefile simply compiles and executes the standalone FetchHeaders java application.

default:

	@javac FetchHeaders.java     # Compiles the source code in to byte code contained in FetchHeaders.class
	@java FetchHeaders           # Executes the byte code
