# This Makefile simply compiles and executes the standalone FetchHeaders java application.

default:

	@javac -cp javax.mail-1.5.0.jar:. FetchHeaders.java     # Compiles the source code in to byte code contained in FetchHeaders.class
	@java -cp javax.mail-1.5.0.jar:. FetchHeaders           # Executes the byte code
